CREATE DATABASE IF NOT EXISTS projetoIOT;
USE projetoIOT;

CREATE TABLE user(
	id INT PRIMARY KEY UNIQUE NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(50) NOT NULL,
    privilege BOOLEAN
);

CREATE TABLE sensor(
	id INT PRIMARY KEY UNIQUE NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    topic VARCHAR(50) NOT NULL,
    value VARCHAR(50) NOT NULL DEFAULT "N/A",
    time_stamp TIMESTAMP NOT NULL DEFAULT "N/A",
    data_type VARCHAR(50) NOT NULL DEFAULT "N/A"
);

CREATE TABLE actuator(
	id INT PRIMARY KEY UNIQUE NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    command_topic VARCHAR(50) NOT NULL,
    status_topic VARCHAR(50) NOT NULL,
    state BOOLEAN NOT NULL DEFAULT false,
    is_default BOOLEAN DEFAULT false
);